# Generated by Django 5.2.6 on 2025-09-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=None, max_length=12, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
